
name: Zip Files
on:
  push:
    paths:
      - 'Working/All Plugins/**'
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Analyse changed plugins
        id: files
        uses: tj-actions/changed-files@v28.0.0
        with:
          separator: '%%%'
      - name: Zip changed plugins
        run: |
          import os
          import subprocess
          changed = "${{ steps.files.outputs.all_changed_and_modified_files }}"
          plugins = set()
          for f in changed.split("%%%"):
            if not "All Plugins" in f:
              continue
            path = f.split(os.sep)
            index = path.index("All Plugins") + 1
            if index >= len(path):
              continue
            plugins.add(path[index])
          if plugins:
            print("The following plugins have changed:")
            for p in plugins:
              print(p)
              subprocess.run(["zip", "-r", p + ".zip", "Working/All Plugins/" + p],
                stdout=subprocess.DEVNULL)
          else:
            print("No plugin changes have been detected.")
        shell: python
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Latest
          release_name: Downloads
          draft: false
          prerelease: false
